### ISSUE TITLE
1.5 Output For Humans and Machines example doesn't work in PowerShell

### ISSUE THREAD

**Issue by mydogisbox** [rust-lang-nursery/cli-wg#118]
The snippet showing how to run the logging example doesn't work in PowerShell.

You can make it work in PowerShell by doing something like:

```
$env:RUST_LOG="info"
cargo run output-log
```

See similar note added to the main Rust book here: https://github.com/rust-lang/book/commit/32ee7141a78e5b66bc5ab31117692e319443c5ae

**Comment by killercup** [comment]
Thanks! Didn't know about that!

Want to make a PR? :)

**Comment by mydogisbox** [comment]
@killercup PR created
