### ISSUE TITLE
Alpha clap man documentation doesn't mention preview status

### ISSUE THREAD

**Issue by liamdawson** [rust-lang-nursery/cli-wg#122]
I was looking into generating man pages for a CLI I'm building, and found [this page](https://rust-lang-nursery.github.io/cli-wg/in-depth/docs.html#rendering-documentation-for-your-cli-apps) as the 7th result for a Google search for `rust cli man pages`. As I was using `StructOpt`, I figured that meant this task would be easy, then I found out that `clap_generate` is a v3 thing.

Suggestion: indicate the document is a preview for anyone else who stumbles across it via Google.

**Comment by Dylan-DPC** [comment]
Thanks :)
