### ISSUE TITLE
Community Survey

### ISSUE THREAD

**Issue by kbknapp** [rust-lang-nursery/cli-wg#13]
<details>
<summary>
As per this conversation on gitter
</summary>

```
Kevin K. @kbknapp: 
> The reason i was asking is that since we are looking at strengthening existing crates, we should know what & who we are targetting
Totally agree!
My opinion (@killercup's could be different, I'm not sure :stuck_out_tongue_winking_eye:) is that if working group can develop a spec proposal for crate improvements, or a spec for non-existing crates and then release these specs to the either the community/crate owners for things that could be worked on it'd be a huge win
There are tons of people in the community that want to help and work on something, but just need to know what to work on, or how it should be built
And you're totally correct, that unless we know what already exists, we can't really determine where the gaps are

Pascal Hertleif @killercup: @kbknapp totally agree! we need to work on defining solutions, ideally with experts in the problem space (like, people who already have crates that do stuff), before implementing (by creating or improving)

Kevin K. @kbknapp: yep, exaclty :thumbsup:

Pascal Hertleif @killercup: i should've probably put a label like "Research Phase" on the current work

Kevin K. @kbknapp: I think it'd be great to get some candid feedback from people like @BurntSushi and @sharkdp (as well as other, like the Exa dev, Habitat devs, and so many more), etc who maintain large production CLIs and see what their pain points were as well as what crates they're currently using.
I know we've already a few of those messages from people in this group, which is invaluable
But maybe another way to get some info would be a quick survey sent out to a targeted few (i.e. known CLI authors), and put out a community call for all CLI authors to participate as well
Cause it's totally understandable that some may not have the time, or even approval, to participate in something like a working group. But a survey should be simple

Pascal Hertleif @killercup: @kbknapp i agree and will try to reach out to some people again (standalone and not as part of "wanna join this working group", just asking for feedback)

Kevin K. @kbknapp: Also, I didn't mean any offense to anyone who I didn't list above...theres so many! I know @Aaronepower has some I use all the time, etc :wink:

Pascal Hertleif @killercup: setting up and evaluating a survey is a lot of work though

Kevin K. @kbknapp: agreed, but I don't think it needs to be super formal or involved. It could be, "what crates are using", "any pain points?", "any strengths", just something to give a more wide reaching audience so we don't accidentally over optimize for a select few
just thoughts :grinning:

Pascal Hertleif @killercup: and they're good thoughts! if someone (you? :grinning:) wants to help with running the survey we can totally do it :grinning:

Dylan DPC @Dylan-DPC: can help if needed :grinning:

Kevin K. @kbknapp: Yeah I can probably help as well, I don't mind giving some feedback on the design of any survey or going over results
Maybe we can start with an initial survey design in the etherpad, cause that's easier for everyone to edit than an issue?

Pascal Hertleif @killercup: @kbknapp @Dylan-DPC great!

Kevin K. @kbknapp: I'll create a tracking issue as well

Pascal Hertleif @killercup: :thumbsup:
```

</details>

We'd like to put together a survey. Ideally we'd like to send this survey out to a number of individuals and organizations specificially, but also open it up to the Rust community to fill out.

I think it'd be a good idea to split this into several "phases"

- [x] Design
- [x] Execution
- :running_man:  Analysis
- [x] Reveal of Results

<details>
<summary>
Legend
</summary>

- [ ] Not started
- :running_woman: In progress
- [x] Complete
</details>

- - -

The design phase will be open and available for all to edit on the ether pad. Once we're happy with the design of the survey we'll move into the execution phase which I for see lasting a minimum of two weeks, potentially a month. In this phase we should post the survey to the subreddit, {u,i}rlo forums, twitter, etc.

Finally the analysis piece will be conducted immediately following execution completion. The analysis piece will last as long as necessary due to participants time, but if at all possible no longer than two weeks.

The results phase will be a "report" of such to the CLI-WG with a proposal of some areas of focus or potential low hanging fruit such as existing gaps in the ecosystem, areas of focus for improvement, etc.

As of now, it's not planned to release these results to the wider community, unless they're interested in the results and of course at the discretion of the Rust team.

--- 

Having said all that, let's begin the design :smile:

**Comment by kbknapp** [comment]
An initial draft of what the survey could look like is up on the etherpad. Please review, edit, discuss, etc. :smile:

**Comment by killercup** [comment]
FTR: [More conversation on Gitter](https://gitter.im/rust-lang/WG-CLI?at=5a8d8fd38f1c77ef3a3839dd)

**Comment by kbknapp** [comment]
I'm about 50% done with my analysis blog post. I'll send it to @killercup once it's complete (hopefully today or tomorrow)

**Comment by kbknapp** [comment]
Survey closes about an hour and half!
