### ISSUE TITLE
Broken link 1.6 testing: fuzzer

### ISSUE THREAD

**Issue by rusty-snake** [rust-lang-nursery/cli-wg#140]
#### where?

https://rust-lang-nursery.github.io/cli-wg/tutorial/testing.html#what-to-test
(A command line app in 15 minutes -> 1.6 testing -> What to test?)

#### which link?

`[fuzzer](https://fuzz.rs/book/introduction.html)`

**Comment by killercup** [comment]
Thanks for the report!

Seems like the fuzz.rs domain is not working anymore? cc @frewsxcv

In the meantime the content is still available at https://github.com/rust-fuzz/book/blob/master/src/introduction.md

**Comment by rusty-snake** [comment]
https://rust-fuzz.github.io/book/
