### ISSUE TITLE
Book: Update links to newer versions of Rust docs

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/cli-wg#156]
Some chapters in the book contain links to The Rust Programming Language book and the standard library docs. To make sure they point to consistent content, we use the fact that these resources are distributed with Rust and link to a specific version, like here:

https://github.com/rust-lang-nursery/cli-wg/blob/82b0b8c5d2e790898d7b33a1fa21136be803fd87/src/tutorial/cli-args.md#L74

Since adding these links, several Rust releases have come and gone. It would be nice to update the links to newer versions (after making sure the content still matches what we want to link to 😄).

**Comment by oylenshpeegul** [comment]
I would be happy to work on this, but does this strategy mean we'll be doing this every six weeks?

**Comment by Dylan-DPC** [comment]
You don't need to for every release.we could do it once every 6 months or maybe look into using /nightly instead

**Comment by killercup** [comment]
Good question. I think six weeks is overkill, but it'd be nice to do it
every once in a while or when we see there are significant updates to the
pages we link to.

**Comment by oylenshpeegul** [comment]
Oops, [https://github.com/rust-lang-nursery/cli-wg/pull/157][(I didn't link to the issue correctly)!
