### ISSUE TITLE
Meeting (2018-03-09 17:00 UTC) 

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/cli-wg#16]
Next meeting is on Friday, march 9, 2018, at 5pm UTC via <https://gitter.im/rust-lang/WG-CLI>.

You can find (and add to) a preliminary agenda on <https://public.etherpad-mozilla.org/p/rust-cli-wg>.

**Comment by uazu** [comment]
I added a point for bottom-line status, because it's common enough that someone will want it sometime.

**Comment by matthiasbeyer** [comment]
Just to make sure: can every interested person attend the meeting? 

And, because I don't know/never used gitter: I can login with github?

**Comment by killercup** [comment]
@matthiasbeyer Yes, and yes!
