### ISSUE TITLE
Slogan

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/cli-wg#3]
In the first meeting, we [discussed](https://github.com/rust-lang-nursery/cli-wg/blob/b02504a38f0d3ea4ab1d049e89cfaa51c39cb66f/logs/2018-02-20-cli-wg-initial-meeting.log#L20-L82) setting a slogan for this working group, to make it easy to describe to others what we're trying to achieve and to remind ourselves what we want to focus on.

I'll post a few proposals below, feel free to add yours.

**Comment by killercup** [comment]
> Frictionlessly creating CLIs with industry best practices (@epage)

**Comment by killercup** [comment]
> Writing CLI apps in Rust is a frictionless experience with known best practices that work across platforms, good documentation, and effortless distribution (@killercup)

**Comment by killercup** [comment]
> Frictionlessly creating world class CLIs (@mattgathu)

**Comment by killercup** [comment]
> Rust makes best-practice CLI applications frictionless through <something> crates and documentation (@epage)

**Comment by kbknapp** [comment]
> Rust makes writing crossplatform, tested, modern CLI applications frictionless while incorporating industry best practices, great documentation, and native performance (@kbknapp)

**Comment by killercup** [comment]
I opened a PR to add an adaptation of @kbknapp's last comment to the Readme: #17. Please review :)
