### ISSUE TITLE
Crate to report diagnostics / contact on unexpected errors

### ISSUE THREAD

**Issue by epage** [rust-lang-nursery/cli-wg#32]
@yoshuawuyts from gitter

On
- panic
- request

Report
- Method to report information
  - email from `Cargo.toml`?
  - repo url from `Cargo.toml`?
- Information to help CLI author
  - OS
  - Rust version
  - Crate version
  - git commit (if possible) in case they are using master rather than a published version

**Comment by yoshuawuyts** [comment]
Made some progress on this https://github.com/yoshuawuyts/human-panic. It now outputs nice messages for humans. I could def use a hand with figuring out what should go into the report. Thanks!

**Comment by epage** [comment]
Human panic and sentry resolve this issue. The main question is if there is anything we should do to raise visibility

**Comment by killercup** [comment]
Assigned to me to remind myself to check if we have things we need to do before the preview and where to document this
