### ISSUE TITLE
assert_cli "next" preview presenting assert_{cmd,fs}

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/cli-wg#40]
- assert_cmd based on predicates
- assert_fs
- first draft of nice guide

**Comment by killercup** [comment]
@epage [said](
https://gitter.im/rust-lang/WG-CLI?at=5b53b42d26bfd636be3d77ae):

> the main blocking issue for assert_fs / assert_cmd is now out for review https://github.com/assert-rs/predicates-rs/pull/0
> 
> Once that is in:
> - Split up predicates crate
> - Create a "0.9" of the predicates crates, assert_fs, and assert_cmd
> - Encourage people to do an API review before going 1.0?

**Comment by epage** [comment]
Looking at the issues to 1.0, I'd be comfortable releasing a 0.9 as soon as my last PR is in.
- https://github.com/assert-rs/assert_fs/milestone/1
- https://github.com/assert-rs/assert_cmd/milestone/1

**Comment by killercup** [comment]
Updated the title to reflect the current goal.

@epage, all that's missing is a blob of text describing what this is and why people should get excited about it. Can you write a few lines?

**Comment by epage** [comment]
`assert_cmd` and `assert_fs` simplify integration testing of your crate with
- Ability to execute your bin and examples
- Setup temp directories for your program to mutate
- Assert on the result of your program and the resulting filesystem changes

**Comment by killercup** [comment]
Thanks! :)
