### ISSUE TITLE
Preview of Man page generation for clap definition

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/cli-wg#42]
Subset of #38

- define a small but somewhat stable API
- example crate that shows the full workflow ("with a build script and everything")

cf. https://github.com/rust-clique/man

**Comment by yoshuawuyts** [comment]
Feel free to assign this to me.

**Comment by killercup** [comment]
Somewhat related as it uses similar code, I wrote a small lib for writing a subset of clap definitions to markdown: https://github.com/rust-clique/clap-md

Maybe we can get a small example project going for Preview 2 that showcases both outputs?

**Comment by killercup** [comment]
code exists and does useful things, but is not released.

see https://github.com/killercup/clap-man-demo for a demo
