### ISSUE TITLE
The "ideal guide" for writing CLI apps in Rust

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/cli-wg#6]
In the first meeting, we [discussed](https://github.com/rust-lang-nursery/cli-wg/blob/b02504a38f0d3ea4ab1d049e89cfaa51c39cb66f/logs/2018-02-20-cli-wg-initial-meeting.log#L150-L160) how to decide what to work on. One approach is writing an "ideal guide".

The basic idea is to write guides about how to write a CLI app in Rust, but not by describing how it works right now, but how we imagine it should work some time in the future.

**Comment by killercup** [comment]
@vitiral [mentioned](https://github.com/rust-lang-nursery/cli-wg/blob/07bf43d0a58843439eef14db90988fee1df1ec7d/logs/2018-02-20-cli-wg-initial-meeting.log#L177) that [the cookbook](https://rust-lang-nursery.github.io/rust-cookbook/) might be a good inspiration.

A concrete example for guides centered around writing CLI apps are the [quicli docs](https://github.com/killercup/quicli/tree/5ec1b649a39e78d5ce4a86c83fa8b8e2e1a94264/docs).

**Comment by vitiral** [comment]
One of the current goals of ergo is [to rewrite the cookbook with zero non-ergo dependencies](https://github.com/rust-crates/ergo/issues/5). I think this will be a useful exercise to see the scope of a crate like ergo. I'm thinking we could take a similar approach here.

**Comment by Dylan-DPC** [comment]
Aim of this issue: 
>  it should be a guide that introduces new users to rust while showing how frictionless writing a cli is and what rust has to offer

**Comment by killercup** [comment]
Since no work has started on this, let's close this and let its idea be reborn in other issues!
