### ISSUE TITLE
Typo in creating new project

### ISSUE THREAD

**Issue by dineshadepu** [rust-lang-nursery/cli-wg#63]
Creating a project by using cargo-generate binary, the command is wrongly spelt.

In `tutorial/setup.md` it is written as 

`cargo generate --git https://github.com/rust-clique/cargo-template-cli`

but should be 

`cargo-generate --git https://github.com/rust-clique/cargo-template-cli`

**Comment by Dylan-DPC** [comment]
Thanks for the issue.

But [cargo generate docs](https://github.com/ashleygwilliams/cargo-generate#usage) 
 say it should be `cargo generate ... `. (and not hyphenated)

**Comment by dineshadepu** [comment]
Okay. It works. I was confused by the binary we installed. The binary name is `cargo-generate`.

**Comment by peddermaster2** [comment]
@dineshadepu In the [v0.1.1 release](https://github.com/ashleygwilliams/cargo-generate/releases/tag/v0.1.1) of cargo-generate it got changed
