### ISSUE TITLE
Decide on a logo!

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/cli-wg#92]
@Aaronepower made some suggesions [on Gitter](https://gitter.im/rust-lang/WG-CLI?at=5bb1e139600c5f6423377b6f):

![](https://files.gitter.im/rust-lang/WG-CLI/UN9X/clique.jpg)
![](https://files.gitter.im/rust-lang/WG-CLI/Kf3V/clique-comparison.jpg)

I'm very happy with this, and unless someone objects or has a another idea, I say we'll go with this one. Maybe you can make a quick PR to add the logo as SVG in the "official" variants to this repo, @Aaronepower? (If you post the bottom center one, I'm sure I can quickly make monochrome/R-less versions.)

cc @Dylan-DPC @spacekookie

**Comment by spacekookie** [comment]
:+1: I like the middle one on the bottom row the most

**Comment by Aaronepower** [comment]
I also have one with no background, which I've grown to prefer.
![clique](https://user-images.githubusercontent.com/4464295/48115415-bbc53e00-e25a-11e8-8748-881ca62f9ab4.png)

**Comment by deg4uss3r** [comment]
I love the rainbow "que" but would it look better in a pixelated font [like this](http://www.identifont.com/samples/core/Pixelette.gif) or something a bit more terminal/system fonty? The cursive just seems to not fit to me, but if I were to choose from the existing ones either middle-bottom or right-bottom. :)

**Comment by Dylan-DPC** [comment]
I'm fine with the bottom-row-middle image as well (or the one of the right)

**Comment by stappersg** [comment]
Happy birthday #92

**Comment by stappersg** [comment]
> Happy birthday #92

On second thought I should have express in another way
_Please decide on logo  (and close this issue that was sleeping for a year)_

**Comment by Dylan-DPC** [comment]
We haven't explicitly mentioned it here but we have picked a logo since we use one for the [twitter_account](https://twitter.com/CliRust). 

Also please take into account that we are all volunteers here and it's common to have issues _sleeping_ for a long time

**Comment by stappersg** [comment]
On Sat, Nov 23, 2019 at 01:18:04PM -0800, Dylan DPC wrote:
> Closed #92.

Tnx
