### ISSUE TITLE
Book: coloring of `ls` output

### ISSUE THREAD

**Issue by jmdyck** [rust-lang-nursery/cli-wg#99]
https://rust-lang-nursery.github.io/cli-wg/in-depth/machine-communication.html
shows some `ls` output, and says "where the last three words are in blue (to show they are folders)."
But the output is all the same color (a middle grey).

At https://github.com/rust-lang-nursery/cli-wg/blob/master/src/in-depth/machine-communication.md , the `ls` output is all blue.

**Comment by killercup** [comment]
Ah yes, this was meant as "if you run this on your machine, the last three items are [highlighted]". Blue is just my terminal setting actually.

Thanks for the report, I'll make this more clear!

**Comment by jmdyck** [comment]
Yup, that looks better.
